### ISSUE TITLE
训练作业失败，报AssertionError: can only join a started process

### ISSUE THREAD

**Issue by hcldadi** [huaweicloud/dls-example#16]
### 基本信息

- Python版本: (2.7)
- MoXing版本：(未使用则不填写)
- 浏览器：Chrome

### 问题描述 / 重现步骤

按照官网的教程，https://support.huaweicloud.com/usermanual-dls/dls_01_0077.html
在ROMA上训练失败

#### 作业基本信息

- 相关作业类型: 
- 作业ID:d2f13d03-cd72-4d60-88cf-15b5e3fad120
- 引擎类型: (TensorFlow or MXNet)
- 运行参数：train_url=s3://final-model; model_name=resnet_v1_50; checkpoint_url=s3://final-model/resnet_v1_50

- 计算节点个数：1
- 计算节点规格：8核|64GiB|1*P100

#### 相关源码 / 输出日志
```
ceback (most recent call last):
  File "/usr/local/anaconda2/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/mind/ci-workspace/tf-model-v1.0.0-dailybuild/moxing/build/moxing/tensorflow/datasets/raw/async_raw_reader.py", line 168, in request_stop
  File "/usr/local/anaconda2/lib/python2.7/multiprocessing/process.py", line 147, in join
    assert self._popen is not None, 'can only join a started process'
AssertionError: can only join a started process
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/local/anaconda2/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/mind/ci-workspace/tf-model-v1.0.0-dailybuild/moxing/build/moxing/tensorflow/datasets/raw/async_raw_reader.py", line 168, in request_stop
  File "/usr/local/anaconda2/lib/python2.7/multiprocessing/process.py", line 147, in join
    assert self._popen is not None, 'can only join a started process'
AssertionError: can only join a started process

```

**Comment by sleepfin** [comment]
能否提供更全的错误信息，真正的错误原因应该在前面

**Comment by sleepfin** [comment]
长时间不活跃，关闭问题。
