### ISSUE TITLE
训练作业错误. InvalidArgumentError: slice index 2 of dimension 0 out of bounds.

### ISSUE THREAD

**Issue by sleepfin** [huaweicloud/dls-example#17]
### 基本信息

- Python版本: 2.7
- MoXing版本：1.0.6
- 浏览器：Chrome

### 问题描述 / 重现步骤

预置模型库 -> ResNet_v1_50 -> 创建训练作业 -> 选择一个数据集并提交作业

#### 作业基本信息

- 相关作业类型: 训练作业
- 作业ID:
- 引擎类型: TensorFlow
- 运行参数：

train_url=s3://zzy/zzy/data/log/carped/
model_name=resnet_v1_50
checkpoint_url=s3://zzy/zzy/pretrained_model/resnet_v1_50/

- 计算节点个数：1
- 计算节点规格：1*P100

#### 相关源码 / 输出日志
```
2018-05-26 15:19:35.802270: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 2 of dimension 0 out of bounds.
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, slice index 2 of dimension 0 out of bounds.
	 [[Node: strided_slice_6 = StridedSlice[Index=DT_INT32, T=DT_INT32, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Shape_2, strided_slice_6/stack, strided_slice_6/stack_1, strided_slice_6/stack_2)]]
INFO:tensorflow:Saving checkpoints for 273 into s3://zzy/zzy/data/log/carped/model.ckpt.
Traceback (most recent call last):
  File "resnet_v1_50_code/finetune_model.py", line 518, in <module>
    main()
  File "resnet_v1_50_code/finetune_model.py", line 514, in main
    export_model=mox.ExportKeys.TF_SERVING)
  File "moxing/tensorflow/executor/learning_builder.pyx", line 375, in moxing.tensorflow.executor.learning_builder.run
  File "moxing/tensorflow/executor/learning_wrapper.pyx", line 228, in moxing.tensorflow.executor.learning_wrapper.LearningWrapper.run
  File "moxing/tensorflow/executor/learning_wrapper.pyx", line 329, in moxing.tensorflow.executor.learning_wrapper.LearningWrapper._profile_train
  File "moxing/tensorflow/executor/learning_wrapper.pyx", line 483, in moxing.tensorflow.executor.learning_wrapper.LearningWrapper._run
  File "moxing/tensorflow/executor/learning.pyx", line 661, in moxing.tensorflow.executor.learning.Learning.run
  File "moxing/tensorflow/executor/learning.pyx", line 1156, in moxing.tensorflow.executor.learning.Learning.training
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 537, in __exit__
    self._close_internal(exception_type)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 574, in _close_internal
    self._sess.close()
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 820, in close
    self._sess.close()
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 941, in close
    ignore_live_threads=True)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1231, in _single_operation_run
    target_list_as_strings, status, None)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 2 of dimension 0 out of bounds.
	 [[Node: strided_slice_6 = StridedSlice[Index=DT_INT32, T=DT_INT32, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Shape_2, strided_slice_6/stack, strided_slice_6/stack_1, strided_slice_6/stack_2)]]

```

**Comment by sleepfin** [comment]
以下是一个简单的数据集检查脚本，可以在notebook中检查一下数据集中的数据是否都符合规范。
```
import sys
import numpy as np
import tensorflow as tf
import moxing.tensorflow as mox
mox.file.set_auth(path_style=True)

img_str = tf.placeholder(dtype=tf.string, shape=())
image = tf.image.decode_image(img_str)
with tf.Session() as sess:

    file_list = mox.file.list_directory('s3://zzy/zzy/data/carped/train/', recursive=True, remove_sep=False)
    total_num_files = len(file_list)
    for img_file in file_list:
        if img_file.endswith('/'):
            continue
        with mox.file.File('s3://zzy/zzy/data/carped/train/' + img_file, 'rb') as f:
            img_stream = f.read()
            image_val = sess.run(image, feed_dict={img_str: img_stream})
            shape = np.shape(image_val)
            if shape[0] < 32 or shape[1] < 32 or shape[2] != 3:
                print('ERROR shape of image %s, %s' % (str(shape), img_file)) 
```
如果有ERROR输出，说明这张图片是有问题的，将其删除再尝试运行。

由于代码比较简单，检查的效率也较低，可能花费很长的时间，请耐心等待。
之后会出一个效率比较高的数据集检查API。
