### ISSUE TITLE
保存模型出现Unable to connect to endpoint错误

### ISSUE THREAD

**Issue by llysuda** [huaweicloud/dls-example#20]
### 基本信息

- Python版本: 3.6
- MoXing版本：(未使用则不填写)
- 浏览器：Chrome

### 问题描述 / 重现步骤

使用的模型是Transformer (paper: Attention is all you need)。
模型大小为1024 units (参数量约382x4 MB) 时，出现错误信息。
模型大小为512 units  (参数量约148x4 MB) 时运行正常。
尝试设置环境变量 S3_REQUEST_TIMEOUT_MSEC 和 S3_REQUEST_TIMEOUT到更大的值，比如6000000，依旧在大模型上出现错误

训练使用的Adam，因此保存checkpoint的时候参数量会更大
如果使用SGD，也不会出现问题

#### 作业基本信息

- 相关作业类型: 
- 作业ID:
- 引擎类型: Tensorflow 1.4
- 运行参数：

- 计算节点个数：1
- 计算节点规格：8xP100

#### 相关源码 / 输出日志

INFO:tensorflow:Create CheckpointSaverHook.
2018-06-30 15:52:46.447723: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:2d:00.0, compute capability: 6.0)
INFO:tensorflow:Saving checkpoints for 1 into s3://mt-models/transformer/model_big/model.ckpt.
2018-06-30 15:55:35.289438: W tensorflow/core/framework/op_kernel.cc:1192] Internal: : Unable to connect to endpoint
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: : Unable to connect to endpoint
	 
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/work/user-job-dir/seq2seq-master/bin/train.py", line 616, in <module>
    tf.app.run()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/work/user-job-dir/seq2seq-master/bin/train.py", line 611, in main
    schedule=schedule)
  File "/home/work/user-job-dir/seq2seq-master/seq2seq/estimator/learn_runner.py", line 219, in run
    return _execute_schedule(experiment, schedule)
  File "/home/work/user-job-dir/seq2seq-master/seq2seq/estimator/learn_runner.py", line 47, in _execute_schedule
    return task()
  File "/home/work/user-job-dir/seq2seq-master/seq2seq/estimator/experiment.py", line 641, in train_and_evaluate
    self.train(delay_secs=0)
  File "/home/work/user-job-dir/seq2seq-master/seq2seq/estimator/experiment.py", line 378, in train
    hooks=self._train_monitors + extra_hooks)
  File "/home/work/user-job-dir/seq2seq-master/seq2seq/estimator/experiment.py", line 823, in _call_train
    hooks=hooks)
  File "/home/work/user-job-dir/seq2seq-master/seq2seq/estimator/estimator.py", line 303, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/work/user-job-dir/seq2seq-master/seq2seq/estimator/estimator.py", line 786, in _train_model
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 521, in run
    run_metadata=run_metadata)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 892, in run
    run_metadata=run_metadata)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 967, in run
    raise six.reraise(*original_exc_info)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 952, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1032, in run
    run_metadata=run_metadata))
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 452, in after_run
    self._save(run_context.session, global_step)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 468, in _save
    self._get_saver().save(session, self._save_path, global_step=step)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1573, in save
    {self.saver_def.filename_tensor_name: checkpoint_file})
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: : Unable to connect to endpoint
	
Caused by op 'save/SaveV2', defined at:
  File "/usr/local/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/work/user-job-dir/seq2seq-master/bin/train.py", line 616, in <module>
    tf.app.run()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/work/user-job-dir/seq2seq-master/bin/train.py", line 611, in main
    schedule=schedule)
  File "/home/work/user-job-dir/seq2seq-master/seq2seq/estimator/learn_runner.py", line 219, in run
    return _execute_schedule(experiment, schedule)
  File "/home/work/user-job-dir/seq2seq-master/seq2seq/estimator/learn_runner.py", line 47, in _execute_schedule
    return task()
  File "/home/work/user-job-dir/seq2seq-master/seq2seq/estimator/experiment.py", line 641, in train_and_evaluate
    self.train(delay_secs=0)
  File "/home/work/user-job-dir/seq2seq-master/seq2seq/estimator/experiment.py", line 378, in train
    hooks=self._train_monitors + extra_hooks)
  File "/home/work/user-job-dir/seq2seq-master/seq2seq/estimator/experiment.py", line 823, in _call_train
    hooks=hooks)
  File "/home/work/user-job-dir/seq2seq-master/seq2seq/estimator/estimator.py", line 303, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/work/user-job-dir/seq2seq-master/seq2seq/estimator/estimator.py", line 783, in _train_model
    log_step_count_steps=self._config.log_step_count_steps) as mon_sess:
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 368, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 673, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 493, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 851, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 856, in _create_session
    return self._sess_creator.create_session()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 554, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 419, in create_session
    self._scaffold.finalize()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 212, in finalize
    self._saver.build()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 742, in _build_internal
    save_tensor = self._AddShardedSaveOps(filename_tensor, per_device)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 381, in _AddShardedSaveOps
    return self._AddShardedSaveOpsForV2(filename_tensor, per_device)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 355, in _AddShardedSaveOpsForV2
    sharded_saves.append(self._AddSaveOps(sharded_filename, saveables))
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 296, in _AddSaveOps
    save = self.save_op(filename_tensor, saveables)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 239, in save_op
    tensors)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1163, in save_v2
    shape_and_slices=shape_and_slices, tensors=tensors, name=name)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): : Unable to connect to endpoint

**Comment by sleepfin** [comment]
从日志看，应该是保存模型时调用的tf.gfile模块与OBS连接中断的问题。一般来说`S3_REQUEST_TIMEOUT_MSEC`可以解决这个问题，请问你是如何设置这个环境变量的。

推荐的设置方法如下：
```
import os 
os.environ['S3_REQUEST_TIMEOUT_MSEC']='600000'
import tensorflow as tf
```
请将环境变量的配置写在import tensorflow之前，再次尝试，如果还能复现问题，再回复这个issue。

**Comment by llysuda** [comment]
@sleepfin 谢谢回复。我原本是在shell脚本里设置的环境变量，我也尝试了你建议，还是出现同样的问题。我在TF1.8上也试了一些，同样的问题，不过多了一点错误信息(循环出现下面两句)：
2018-07-03 09:00:59.983663: I tensorflow/core/platform/s3/aws_logging.cc:54] Found secret key
2018-07-03 09:00:59.983805: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.

**Comment by llysuda** [comment]
@sleepfin 这是一个测试程序
[seq2seq-master_test_s3.py.txt](https://github.com/huaweicloud/dls-example/files/2172324/seq2seq-master_test_s3.py.txt)
程序中的参数量跟我的模型差不多，也会出现同样的问题。

PS：TF保存模型到S3时好像会先缓存到本地？也就是任务的docker里，下面是TF的一段源码 ：
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/s3/s3_file_system.cc#L213
不知道跟这点有没有关系……

**Comment by sleepfin** [comment]
简单描述一下问题：
tf-1.4下，由于未知bug引起gfile无法连接s3，经过验证后，我发现该问题在tf-1.8中被修复。

但是在tf-1.8上会遇到新问题，即`/tmp`目录太小无法写临时文件（TF源码写死，无法重定向）

目前我能想到的规避方法是，在tf-1.4下修改代码，把保存模型的操作放在容器挂载的SSD中，然后再做一次同步到OBS的操作，我在你提供的代码上做了一些修改如下：

```
...
checkpoint_s3_dir = 's3://dls-test/log/liliangyou-1'
WINDOW_SIZE = 1
BATCH_SIZE = 1
MAX_VOCAB_SIZE = 160000
HIDDEN_DIM = 1024
NUM_LAYERS = 12
NUM_CLASSES = 60000
NUM_PARTITIONS = 10

# ---------------- Modify code begin ----------------
import moxing as mox
tf.logging.set_verbosity(tf.logging.INFO)


class CheckpointSyncToOBSHook(tf.train.CheckpointSaverHook):
  def _save(self, session, step):
    super(CheckpointSyncToOBSHook, self)._save(session, step)
    log_files_list = mox.file.list_directory(self._checkpoint_dir)
    ckpt_files_list = []
    cur_ckpt_file_prefix = '%s-%d' % (self._save_path, step)
    for log_file in log_files_list:
      abs_log_file = os.path.join(self._checkpoint_dir, log_file)
      if abs_log_file.startswith(cur_ckpt_file_prefix):
        ckpt_files_list.append(log_file)
    tf.logging.info('Uploading checkpoints from local to OBS...')
    tf.logging.info(ckpt_files_list)
    mox.file.copy_parallel(self._checkpoint_dir, checkpoint_s3_dir, file_list=ckpt_files_list)

# ---------------- Modify code end ----------------


def partitioned_embeddings(embedding_dim):
  # Randomly generate embedding
  partitioner = tf.fixed_size_partitioner(NUM_PARTITIONS, axis=0)
  return tf.get_variable(
    name="embedding",
    shape=[MAX_VOCAB_SIZE, HIDDEN_DIM],
    partitioner=partitioner,
    dtype=tf.float32)
...
  estimator = tf.estimator.Estimator(model_fn=model_fn, params={'embedding_dim': HIDDEN_DIM},
                                     config=RunConfig(model_dir=model_dir))

  # ---------------- Modify code begin ----------------
  local_cache_path = os.environ['DLS_LOCAL_CACHE_PATH']
  estimator.train(input_fn=input_fn,
                  hooks=[CheckpointSyncToOBSHook(checkpoint_dir=local_cache_path, save_secs=600)])
  # ---------------- Modify code end ----------------
...
```

这只能是个临时的规避方法，更好的解决办法应该是用户代码不感知的，我们这边也记录了这个问题后续持续跟踪。

提供修改后的代码文件：
[seq2seq-master_test_s3.py.txt](https://github.com/huaweicloud/dls-example/files/2175263/seq2seq-master_test_s3.py.txt)

**Comment by llysuda** [comment]
@sleepfin 多谢多谢，这个方法可以解决问题。
