### ISSUE TITLE
numpy.load读文件失败

### ISSUE THREAD

**Issue by zhengpengpeng** [huaweicloud/dls-example#23]
### 基本信息

- Python版本: (2.7 / 3.6)
- MoXing版本：(未使用则不填写)
- 浏览器：

### 问题描述 / 重现步骤

(简单描述问题信息，如果是bug，请描述重现步骤)

#### 作业基本信息

- 相关作业类型: 训练
- 作业ID:prejob-92946102
- 引擎类型: TensorFlow
- 运行参数：

- 计算节点个数：1
- 计算节点规格：8核|64GiB|1*P100

#### 相关源码 / 输出日志
```
INFO:tensorflow:RGB checkpoint restored
Traceback (most recent call last):
  File "kinetics-i3d-master/evaluate_sample.py", line 146, in <module>
    tf.app.run(main)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "kinetics-i3d-master/evaluate_sample.py", line 113, in main
    rgb_sample = np.load(_SAMPLE_PATHS['rgb'])
  File "/usr/local/anaconda2/lib/python2.7/site-packages/numpy/lib/npyio.py", line 372, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: 's3://bucket-3216/train_data/data/v_CricketShot_g04_c01_rgb.npy'
```

**Comment by sleepfin** [comment]
#19 
试试：
```
np.load(mox.file.read(_SAMPLE_PATHS['rgb'], binary=True))
```
或者：
```
with mox.file.File(_SAMPLE_PATHS['rgb'], 'rb') as f:
  np.load(f)
```

**Comment by sleepfin** [comment]
如果还有新的问题，请reoprn此issue

**Comment by sleepfin** [comment]
#8
