### ISSUE TITLE
运行pytorch作业出现错误 RuntimeError: unable to write to file

### ISSUE THREAD

**Issue by sleepfin** [huaweicloud/dls-example#26]
### 基本信息

- Python版本: (2.7 / 3.6)
- MoXing版本：(未使用则不填写)
- 浏览器：

### 问题描述 / 重现步骤

提交基于pytorch的训练作业时，遇到如下错误：

```
RuntimeError: unable to write to file </torch_76_3625483894> at /pytorch/aten/src/TH/THAllocator.c:383
```

#### 作业基本信息

- 相关作业类型: 训练作业
- 作业ID:
- 引擎类型: pytorch
- 运行参数：

- 计算节点个数：
- 计算节点规格：

#### 相关源码 / 输出日志

```
Traceback (most recent call last):
  File "pytorch/main.py", line 205, in <module>
    main()
  File "pytorch/main.py", line 116, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "pytorch/main.py", line 136, in train
    for i, (input, target) in enumerate(train_loader):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 113, in default_collate
    storage = batch[0].storage()._new_shared(numel)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/storage.py", line 114, in _new_shared
    return cls._new_using_filename(size)
RuntimeError: unable to write to file </torch_76_3625483894> at /pytorch/aten/src/TH/THAllocator.c:383

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 35, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 178, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 87) is killed by signal: Bus error.
```

**Comment by sleepfin** [comment]
根据pytorch源码

https://github.com/pytorch/pytorch/blob/4a6fbf03c62bcfbfdc60d955b48f5c44bfe42173/torch/csrc/generic/StorageSharing.cpp#L41

pytorch将共享内存的临时文件保存在了`/torch_xxx`文件中，即容器中的根目录下。容器磁盘空间不足导致该问题的发生。目前可以通过以下代码暂时关闭pytorch的shared memory功能来规避：

将此代码贴到你启动代码的最前面：

```
import sys
import torch
from torch.utils.data import dataloader
from torch.multiprocessing import reductions
from multiprocessing.reduction import ForkingPickler

default_collate_func = dataloader.default_collate


def default_collate_override(batch):
  dataloader._use_shared_memory = False
  return default_collate_func(batch)

setattr(dataloader, 'default_collate', default_collate_override)

for t in torch._storage_classes:
  if sys.version_info[0] == 2:
    del ForkingPickler.dispatch[t]
  else:
    del ForkingPickler._extra_reducers[t]
```

**Comment by sleepfin** [comment]
社区issue跟踪：https://github.com/pytorch/pytorch/issues/10396

**Comment by sleepfin** [comment]
目前已经将pytorch作为单独引擎了，该问题已解决

**Comment by njustymk** [comment]
非常感谢解答。
