### ISSUE TITLE
公有云运行TensorFlow训练作业出现错误：truncated record at xxxxx

### ISSUE THREAD

**Issue by HydrogenQAQ** [huaweicloud/dls-example#29]
### 基本信息

- Python版本: (2.7 / 3.6)
- MoXing版本：(未使用则不填写)
- 浏览器：

### 问题描述 / 重现步骤

在公有云上提交训练作业(比如冰山识别项目)， 训练过程中连接obs读取tfrecord数据时出现错误，报错信息大致如下所示：

```
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.DataLossError'>, truncated record at 9832454
	 [[Node: parallel_read/ReaderReadV2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/device:CPU:0"](parallel_read/TFRecordReaderV2, parallel_read/filenames)]]
```

#### 作业基本信息

- 相关作业类型: 训练作业
- 作业ID:
- 引擎类型: TensorFlow
- 运行参数：

- 计算节点个数：
- 计算节点规格：

#### 相关源码 / 输出日志
```
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.DataLossError'>, truncated record at 9832454
	 [[Node: parallel_read/ReaderReadV2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/device:CPU:0"](parallel_read/TFRecordReaderV2, parallel_read/filenames)]]
2018-08-30 13:29:29.379592: W tensorflow/core/framework/op_kernel.cc:1192] Internal: : Unable to connect to endpoint
Traceback (most recent call last):
  File "code/train_iceberg.py", line 164, in <module>
    save_model_secs=120) 
  File "moxing/tensorflow/executor/learning_builder.pyx", line 379, in moxing.tensorflow.executor.learning_builder.run
  File "moxing/tensorflow/executor/learning_wrapper.pyx", line 228, in moxing.tensorflow.executor.learning_wrapper.LearningWrapper.run
  File "moxing/tensorflow/executor/learning_wrapper.pyx", line 287, in moxing.tensorflow.executor.learning_wrapper.LearningWrapper._profile_train
  File "moxing/tensorflow/executor/learning_wrapper.pyx", line 484, in moxing.tensorflow.executor.learning_wrapper.LearningWrapper._run
  File "moxing/tensorflow/executor/learning.pyx", line 649, in moxing.tensorflow.executor.learning.Learning.run
  File "moxing/tensorflow/executor/learning.pyx", line 1117, in moxing.tensorflow.executor.learning.Learning.training
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 537, in __exit__
    self._close_internal(exception_type)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 574, in _close_internal
    self._sess.close()
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 820, in close
    self._sess.close()
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 941, in close
    ignore_live_threads=True)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1231, in _single_operation_run
    target_list_as_strings, status, None)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.DataLossError: truncated record at 9832454
	 [[Node: parallel_read/ReaderReadV2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/device:CPU:0"](parallel_read/TFRecordReaderV2, parallel_read/filenames)]]
```

**Comment by HydrogenQAQ** [comment]
在定位过程中发现，该问题是由于tf.gfile接口连接公有云obs不稳定，导致最终tfrecord数据无法读取到。

目前的规避方法是通过obs的sdk先将obs中的数据拷贝到服务器cache文件夹下，再从cache文件夹进行数据读取。

针对冰山识别代码具体的改动如下所示：
```
dataset = mox.get_tfrecord(dataset_dir=flags.data_url,
                             file_pattern=file_pattern,
                             num_samples=num_samples,
                             keys_to_features=keys_to_features,
                             items_to_handlers=items_to_handlers,
                             num_epochs=num_epochs,
                             shuffle=shuffle)
```
源代码是直接根据flags.data_url参数进行一个读取，现改动为：

先在代码最前面加上，
`mox.file.copy_parallel(src_url=flags.data_url, dst_url='/cache')`，再改动：
```
dataset = mox.get_tfrecord(dataset_dir=‘/cache’,
                             file_pattern=file_pattern,
                             num_samples=num_samples,
                             keys_to_features=keys_to_features,
                             items_to_handlers=items_to_handlers,
                             num_epochs=num_epochs,
                             shuffle=shuffle)
```
