### ISSUE TITLE
callback保存训练模型报错

### ISSUE THREAD

**Issue by 1071034024** [huaweicloud/dls-example#39]
### 基本信息

- Python版本: ( 3.6)
- MoXing版本：(未使用则不填写)
- 浏览器：

### 问题描述 / 重现步骤

(简单描述问题信息，如果是bug，请描述重现步骤)

#### 作业基本信息

- 相关作业类型: 
- 作业ID:
- 引擎类型: (TensorFlow or MXNet)
- 运行参数：

- 计算节点个数：
- 计算节点规格：

#### 相关源码 / 输出日志
```
Traceback (most recent call last):
  File "CnnModel/DCNN.py", line 152, in <module>
    model = cnn_model()
  File "CnnModel/DCNN.py", line 66, in cnn_model
    callbacks=[check],
  File "/usr/local/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1042, in fit
    validation_steps=validation_steps)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 219, in fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/keras/callbacks.py", line 77, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/callbacks.py", line 452, in on_epoch_end
    filepath = self.filepath.format(epoch=epoch + 1, **logs)
AttributeError: 'File' object has no attribute 'format'
```

**Comment by sleepfin** [comment]
这个是用户代码本身问题，关闭issue
