### ISSUE TITLE
读取.npy/.npz文件报错

### ISSUE THREAD

**Issue by SenZHANG-GitHub** [huaweicloud/dls-example#42]
### 基本信息

- Python版本: (3.6)
- MoXing版本：(未使用则不填写)
- 浏览器：

### 问题描述 / 重现步骤

Error when reading .npy/.npz files using moxing

Error log：
Traceback (most recent call last):
  File "src/main_kaggle.py", line 12, in <module>
    train_img, train_mask = read_train_data(mod)
  File "/home/work/user-job-dir/src/data_util.py", line 18, in read_train_data
    X_train = np.load(mox.file.read('s3://bucket-medical/ISLES/npy_data/train_'+MODULE_SELECTED+'_img.npy', binary=True))
  File "/usr/local/anaconda3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 404, in load
    magic = fid.read(N)
AttributeError: 'bytes' object has no attribute 'read'

#### 作业基本信息

- 相关作业类型: 
- 作业ID:
- 引擎类型: (TensorFlow)
- 运行参数：

- 计算节点个数：
- 计算节点规格：

#### 相关源码 / 输出日志
Source code： 
X_train = np.load(mox.file.read('s3://bucket-medical/ISLES/npy_data/train_'+MODULE_SELECTED+'_img.npy', binary=True))

Error log：
Traceback (most recent call last):
  File "src/main_kaggle.py", line 12, in <module>
    train_img, train_mask = read_train_data(mod)
  File "/home/work/user-job-dir/src/data_util.py", line 18, in read_train_data
    X_train = np.load(mox.file.read('s3://bucket-medical/ISLES/npy_data/train_'+MODULE_SELECTED+'_img.npy', binary=True))
  File "/usr/local/anaconda3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 404, in load
    magic = fid.read(N)
AttributeError: 'bytes' object has no attribute 'read'

**Comment by SenZHANG-GitHub** [comment]
I have fixed this issue.

Reason: mox.file.read returns a byte string of the data directly! Two ways to solve it,

(1) import io, then use io.BytesIO to transform the input, (recommended)
     e.g. X_train = np.load(io.BytesIOmox.file.read('s3://bucket-test/test/npy_data/train_CT_img.npy', binary=True)))

(2) Alternatively we can use np.fromstring to directly process the string returned by mox.file.read. But remember to remove the first 128 bytes which are the header information of .npy rather than your data. Also, remember to specify the dtype of the npy data. Then use np.reshape to get the correct shape.
    e.g.  xstr = np.fromstring(mox.file.read('s3://bucket-test/test/npy_data/train_CT_img.npy', binary=True), dtype=np.int32)
            X_train = np.reshape(xstr[32:], (502, 256, 256, 1))
 (Here because dtype=int32, therefore the first 128 bytes of header information are store in xstr[:32], and the original size of my data is (502, 256, 256, 1))
