### ISSUE TITLE
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'num_gpus'

### ISSUE THREAD

**Issue by gallupliu** [huaweicloud/dls-example#48]
### 基本信息

- Python版本: ( 3.6)
- MoXing版本：(未使用则不填写)
- 浏览器：chrome

### 问题描述 / 重现步骤
使用num_gpus = mox.get_flag('num_gpus')，出现错误
(简单描述问题信息，如果是bug，请描述重现步骤)

#### 作业基本信息

- 相关作业类型: 
- 作业ID:
- 引擎类型: (TensorFlow)
- 运行参数：

- 计算节点个数：1
- 计算节点规格：16核|128GiB|2*P100

#### 相关源码 / 输出日志
```
WARNING:root:Use of the keyword argument names (flag_name, default_value, docstring) is deprecated, please use (name, default, help) instead.
WARNING:root:Use of the keyword argument names (flag_name, default_value, docstring) is deprecated, please use (name, default, help) instead.
Traceback (most recent call last):
  File "bert/run_classifier_new.py", line 760, in <module>
    main()
  File "bert/run_classifier_new.py", line 608, in main
    if not flags.do_train and not flags.do_eval and not flags.do_predict:
  File "/home/work/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/flags.py", line 84, in __getattr__
    wrapped(_sys.argv)
  File "/home/work/anaconda3/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 630, in __call__
    name, value, suggestions=suggestions)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'num_gpus'
```

**Comment by sleepfin** [comment]
请参考：#7

**Comment by huaweiclouddev** [comment]
## 🤖 Stale Bot

⏰ 已 2807 天无活动，标记为过期。如有更新将自动取消。30 天后无活动将自动关闭。

<sub>集中管理 · 详见 [治理规范](https://github.com/huaweicloud/.github/blob/main/GOVERNANCE.md)</sub>

**Comment by huaweiclouddev** [comment]
## 🤖 Stale Bot

🔒 因 35 天无活动自动关闭。如需重新打开请评论。

<sub>集中管理 · 详见 [治理规范](https://github.com/huaweicloud/.github/blob/main/GOVERNANCE.md)</sub>
