### ISSUE TITLE
训练作业提示：数据集找不到，No such file or directory

### ISSUE THREAD

**Issue by Charliechow** [huaweicloud/dls-example#8]
### 基本信息

- Python版本: 2.7
- MoXing版本：
- 浏览器：

### 问题描述 / 重现步骤

训练数据集在OBS上存在，创建训练作业填写data_url为OBS路径，训练失败，提示:No such file or directory

#### 作业基本信息

- 相关作业类型: 训练作业
- 作业ID:
- 引擎类型: TensorFlow
- 运行参数：

- 计算节点个数：
- 计算节点规格：

#### 相关源码 / 输出日志
日志截图：
![image](https://user-images.githubusercontent.com/31006199/39036695-e3b82974-44b0-11e8-9306-bd9994b147e4.png)

相关代码：
```
  if not gfile.Exists(image_dir):
    print("Image directory '" + image_dir + "' not found.")
    return None
  result = {}
  sub_dirs = [x[0] for x in os.walk(image_dir)]
```

**Comment by sleepfin** [comment]
sub_dirs = [x[0] for x in os.walk(image_dir)]

DLS服务中不能使用os.walk访问OBS文件系统，替换为tf.gfile.Walk

在DLS中，对文件系统的操作，如果是对路径字符串本身的操作，是可以使用os的，比如os.path.join，如果涉及文件系统的连接，都要用gfile来操作，如walk, listdir, exists, glob

用户在训练脚本中想读取一些文件或者写入一些日志文件，发现找不到文件或路径。

如果你想读取OBS上桶名为dls-test中的文件a.txt，而且使用了如下代码：

    f=open('/dls-test/a.txt', 'r')

则会出现如下错误：

    IOError: [Errno 2] No such file or directory: '/dls-test/a.txt'


在DLS服务中，作业在容器中启动，一般来说对文件的读写都是基于OBS或其他数据服务的，比如打开一个OBS上，桶名为dls-test中的文件a.txt，那么要使用OBS的路径s3://dls-test/a.txt，但是当你发现把代码修改为：

    f=open('s3://dls-test/a.txt', 'r')

依然会出现同样找不到文件的错误，那是因为大多数文件读写的API都不支持s3路径，用户如果涉及文件读写的操作，都必须使用支持s3的文件接口，如obs-sdk, obscmd, s3cmd, tf.gfile, mox.file

以下代码利用tf.gfile操作文件：

    import tensorflow as tf
    f=tf.gfile.Open('s3://dls-test/a.txt', 'r')

在DLS中，用户不需要配置OBS的ak, sk等信息，这些都已经默认配置好了。

**Comment by sleepfin** [comment]
另外，以下代码是不支持S3路径的
```
import logging

logging.basicConfig(level=logging.DEBUG, filename='s3://dls-test/zzy/log/logging.txt', filemode='w')
console = logging.StreamHandler()
console.setLevel(logging.INFO)
logging.getLogger('').addHandler(console)

logging.info('hello world')
```

将代码修改正确：
```
import logging
import moxing as mox

stream = mox.file.File('s3://dls-test/zzy/log/logging.txt', 'w')
logging.basicConfig(level=logging.DEBUG, stream=stream)
console = logging.StreamHandler()
console.setLevel(logging.INFO)
logging.getLogger('').addHandler(console)

logging.info('hello world')
stream.close()
```
在最后一定记得将stream关闭，才能保证日志文件正确输出到OBS了

**Comment by sleepfin** [comment]
将logging重定向到OBS后，出现如下错误：

```
Logged from file file_io.py, line 237
Traceback (most recent call last):
  File "/usr/local/anaconda2/lib/python2.7/logging/__init__.py", line 885, in emit
    self.flush()
  File "/usr/local/anaconda2/lib/python2.7/logging/__init__.py", line 845, in flush
    self.stream.flush()
  File "/home/mind/ci-workspace/moxing-mxnet-1.1-dailybuild/moxing/build/moxing/framework/file/file_io.py", line 1528, in flush
  File "/home/mind/ci-workspace/moxing-mxnet-1.1-dailybuild/moxing/build/moxing/framework/file/file_io.py", line 1248, in flush
  File "/home/mind/ci-workspace/moxing-mxnet-1.1-dailybuild/moxing/build/moxing/framework/file/file_io.py", line 571, in _append_obs
  File "/usr/local/anaconda2/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/usr/local/anaconda2/lib/python2.7/multiprocessing/pool.py", line 161, in __init__
    self._repopulate_pool()
  File "/usr/local/anaconda2/lib/python2.7/multiprocessing/pool.py", line 225, in _repopulate_pool
    w.start()
  File "/usr/local/anaconda2/lib/python2.7/multiprocessing/process.py", line 124, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children
Logged from file file_io.py, line 237
Traceback (most recent call last):
  File "/usr/local/anaconda2/lib/python2.7/logging/__init__.py", line 885, in emit
    self.flush()
  File "/usr/local/anaconda2/lib/python2.7/logging/__init__.py", line 845, in flush
    self.stream.flush()
  File "/home/mind/ci-workspace/moxing-mxnet-1.1-dailybuild/moxing/build/moxing/framework/file/file_io.py", line 1528, in flush
  File "/home/mind/ci-workspace/moxing-mxnet-1.1-dailybuild/moxing/build/moxing/framework/file/file_io.py", line 1248, in flush
  File "/home/mind/ci-workspace/moxing-mxnet-1.1-dailybuild/moxing/build/moxing/framework/file/file_io.py", line 571, in _append_obs
  File "/usr/local/anaconda2/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/usr/local/anaconda2/lib/python2.7/multiprocessing/pool.py", line 161, in __init__
    self._repopulate_pool()
  File "/usr/local/anaconda2/lib/python2.7/multiprocessing/pool.py", line 225, in _repopulate_pool
    w.start()
  File "/usr/local/anaconda2/lib/python2.7/multiprocessing/process.py", line 124, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children
```

**Comment by sleepfin** [comment]
有可能是在子线程/进程中使用了logging，由于append操作会创建进程池和子进程，`daemonic processes`无法在子进程/线程中被创建。

解决办法，把以下代码贴到运行代码的最前面：

```
import multiprocessing
from multiprocessing import Process
from multiprocessing.pool import Pool


class NoDaemonProcess(Process):
  def _get_daemon(self):
    return False

  def _set_daemon(self, value):
    pass

  daemon = property(_get_daemon, _set_daemon)


class NoDaemonPool(Pool):
  Process = NoDaemonProcess

setattr(multiprocessing, 'Pool', NoDaemonPool)
```

**Comment by sleepfin** [comment]
用cv2从OBS读取一张图片：

```
import cv2
import numpy as np
import moxing as mox
img = cv2.imdecode(np.fromstring(mox.file.read('s3://dls-test/xxx.jpg', binary=True), np.uint8), cv2.IMREAD_COLOR)
```
